Korjattu opetus-metadatan käsittely
Opetushallitus/kouta-internal pull request #32
Opened 2021-05-25 18:19 UTC by augustk

2021-06-09 12:16 UTC, vesaruu commented on README.md
> +Lokaalin postgres-kannan voi käynnistää dockerilla (sen jälkeen kun kouta-internalin oma kontti-image on buildattu):
EmbeddedJettyLauncher käynnistää automaattisesti postgres-kontin, joten tätä ei ehkä tarvitsisi olla. Se tosin taitaa tsekata että onko jo käynnissä, ja jos on, niin ei tee mitään eli ei tästä haittaakaan taida olla. Elastic-konttia ei osaa käynnistää automaattisesti joten siksi on tuossa ylempänä siitä ohje.

2021-06-09 12:23 UTC, vesaruu commented on README.md
> +Lokaalin postgres-kannan voi käynnistää dockerilla (sen jälkeen kun kouta-internalin oma kontti-image on buildattu):
Niin ja se tosiaan käynnistää postgresin random vapaaseen porttiin.

2021-06-29 08:40 UTC, Humakt83 requested changes

2021-06-29 08:40 UTC, Humakt83 commented on src/main/scala/fi/oph/kouta/internal/util/json.scala
> +    //.withStrictOptionParsing
Tämän kommentin voisi poistaa

2021-06-29 11:38 UTC, Humakt83 approved these changes

2021-06-29 11:45 UTC, merged